project_id = "ryjvwimnteinqaxpmkfk"

[functions.generate-pitch]
verify_jwt = false

[functions.generate-speech]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.elevenlabs-stt]
verify_jwt = false

[functions.get-analytics]
verify_jwt = false

[functions.structure-script]
verify_jwt = false

[functions.evaluate-hackathon-jury-pitch]
verify_jwt = false
